# Generated by Django 5.2b1 on 2025-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_otp',
            field=models.BooleanField(default=False),
        ),
    ]
