import { User, Member, AuditLog } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@iete.org',
    role: 'admin',
    verified: true,
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'member',
    membershipId: 'IETE2023001',
    phoneNumber: '+91-9876543210',
    verified: true,
  },
  {
    id: '3',
    name: 'Jane Doe',
    email: 'jane@example.com',
    role: 'member',
    membershipId: 'IETE2023002',
    phoneNumber: '+91-9876543211',
    verified: true,
  },
  {
    id: '4',
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'member',
    membershipId: 'IETE2023003',
    phoneNumber: '+91-9876543212',
    verified: true,
  },
  {
    id: '5',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'member',
    membershipId: 'IETE2023004',
    phoneNumber: '+91-9876543213',
    verified: true,
  },
  {
    id: '6',
    name: 'Mike Brown',
    email: 'mike@example.com',
    role: 'member',
    membershipId: 'IETE2023005',
    phoneNumber: '+91-9876543214',
    verified: true,
  },
  {
    id: '7',
    name: 'Emily Davis',
    email: 'emily@example.com',
    role: 'member',
    membershipId: 'IETE2023006',
    phoneNumber: '+91-9876543215',
    verified: true,
  },
  {
    id: '8',
    name: 'David Lee',
    email: 'david@example.com',
    role: 'member',
    membershipId: 'IETE2023007',
    phoneNumber: '+91-9876543216',
    verified: true,
  },
  {
    id: '9',
    name: 'Sarah Taylor',
    email: 'sarah@example.com',
    role: 'member',
    membershipId: 'IETE2023008',
    phoneNumber: '+91-9876543217',
    verified: true,
  },
];

export const mockMembers: Member[] = [
  {
    id: '1',
    userId: '2',
    membershipId: 'IETE2023001',
    temporaryNumber: 'TEMP001',
    status: 'active',
    type: 'professional',
    joinDate: '2023-08-15',
    paymentStatus: 'paid',
  },
  {
    id: '2',
    userId: '3',
    membershipId: 'IETE2023002',
    temporaryNumber: 'TEMP002',
    status: 'active',
    type: 'student',
    joinDate: '2023-08-16',
    paymentStatus: 'paid',
  },
  {
    id: '3',
    userId: '4',
    membershipId: 'IETE2023003',
    temporaryNumber: 'TEMP003',
    status: 'active',
    type: 'professional',
    joinDate: '2023-08-17',
    paymentStatus: 'paid',
  },
  {
    id: '4',
    userId: '5',
    membershipId: 'IETE2023004',
    temporaryNumber: 'TEMP004',
    status: 'active',
    type: 'student',
    joinDate: '2023-08-18',
    paymentStatus: 'paid',
  },
  {
    id: '5',
    userId: '6',
    membershipId: 'IETE2023005',
    temporaryNumber: 'TEMP005',
    status: 'active',
    type: 'professional',
    joinDate: '2023-08-19',
    paymentStatus: 'paid',
  },
  {
    id: '6',
    userId: '7',
    membershipId: 'IETE2023006',
    temporaryNumber: 'TEMP006',
    status: 'active',
    type: 'student',
    joinDate: '2023-08-20',
    paymentStatus: 'paid',
  },
  {
    id: '7',
    userId: '8',
    membershipId: 'IETE2023007',
    temporaryNumber: 'TEMP007',
    status: 'active',
    type: 'professional',
    joinDate: '2023-08-21',
    paymentStatus: 'paid',
  },
  {
    id: '8',
    userId: '9',
    membershipId: 'IETE2023008',
    temporaryNumber: 'TEMP008',
    status: 'active',
    type: 'student',
    joinDate: '2023-08-22',
    paymentStatus: 'paid',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    action: 'User Registration',
    userId: '2',
    timestamp: '2023-08-15T10:30:00Z',
    details: 'New user registered with email john@example.com',
  },
  {
    id: '2',
    action: 'Membership Application',
    userId: '3',
    timestamp: '2023-08-16T11:00:00Z',
    details: 'Membership application submitted by user with email jane@example.com',
  },
  {
    id: '3',
    action: 'Payment Received',
    userId: '4',
    timestamp: '2023-08-17T12:00:00Z',
    details: 'Payment received from user with email bob@example.com',
  },
  {
    id: '4',
    action: 'User Login',
    userId: '5',
    timestamp: '2023-08-18T13:00:00Z',
    details: 'User logged in with email alice@example.com',
  },
  {
    id: '5',
    action: 'Membership Approval',
    userId: '6',
    timestamp: '2023-08-19T14:00:00Z',
    details: 'Membership approved for user with email mike@example.com',
  },
  {
    id: '6',
    action: 'User Profile Update',
    userId: '7',
    timestamp: '2023-08-20T15:00:00Z',
    details: 'User profile updated by user with email emily@example.com',
  },
  {
    id: '7',
    action: 'Password Reset',
    userId: '8',
    timestamp: '2023-08-21T16:00:00Z',
    details: 'Password reset by user with email david@example.com',
  },
  {
    id: '8',
    action: 'Membership Renewal',
    userId: '9',
    timestamp: '2023-08-22T17:00:00Z',
    details: 'Membership renewed by user with email sarah@example.com',
  },
];